### ISSUE TITLE
Items/Blocks not dropping (1.19.2)

### ISSUE THREAD

**Issue by Hir0shiyt** [Emafire003/LightWithin#21]
Blocks I break or Items I throw don't show up on the world, they just disappear, so I can't get items at all.

**To Reproduce**
1. Break a block or throw an item
2. Nothing drops

**Version information**
LightWithin mod version: <1.1.2>
Minecraft Version: <1.19.2>
Fabric API version: <0.77.0 - 1.19.2>

(Usually not required, but could be helpful if you want)
Dependencies version: <No dependencies>

**Expected behavior**
Items and blocks dropping normally.

**Screenshots and files**
[2024-07-12-2.log](https://github.com/user-attachments/files/16196366/2024-07-12-2.log)

**Additional context**
I don't honestly know if it's a problem with another mod, but if it is, I'd appreciate it if you tried to fix it since I like the mod and can't imagine playing without it, until then. Thanks for taking your time to read this.

**Comment by Emafire003** [comment]
I don't think it's an issue with LightWithin, looks more like an issue with the _apoli_ mod or something like that. It throws this error: `[15:31:31] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2846@555e523f, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "id" is null
	at io.github.apace100.apoli.power.ReplaceLootTablePower.hasReplacement(ReplaceLootTablePower.java:58) ~[apoli-2.6.1-b666438ef8105be6.jar:?]
	at net.minecraft.class_52.mdb6f56c$apoli$lambda$modifyLootTable$0$1(class_52.java:1078) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraft.class_52.handler$zbj000$apoli$modifyLootTable(class_52.java:1080) ~[client-intermediary.jar:?]
	at net.minecraft.class_52.method_328(class_52.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_52.method_320(class_52.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_52.method_319(class_52.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9560(class_4970.java:268) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26189(class_4970.java:960) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9609(class_2248.java:339) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9511(class_2248.java:365) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9556(class_2248.java:444) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:228) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:203) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1092) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$bbd000$c2me-opts-scheduling$redirectExecuteTask(class_1255.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:14277) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by Emafire003** [comment]
Yes I can confirm it's not an issue with LightWithin, or the very least I can't reproduce it. Most likely some other mod is conflicting with Origins/Apoli (their library) in the modification of loot tables and for some reason it corrupts the player interaction event.

**Comment by Hir0shiyt** [comment]
Then I already know what it is, I was suspicious of this mod because when I uninstalled it, the drops worked normally, I'll report this to the End Game Origins dev, thanks again for taking your time to read this.
